# jira Exporter Workflow
# This workflow is responsible for running jira exporter.
# jira_host: The URL of your Jira, for example: https://example.atlassian.net
# atlassian_user_email: The email of the user used to query Jira
# atlassian_user_token: The API token generated in your Atlassian account

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  run-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Set a time limit for the job

    steps:
      - name: Run Jira Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: jira
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.port.io"
          config: |
            jira_host: "https://ashwiniisudheer.atlassian.net"
            atlassian_user_email: ${{ secrets.atlassianUserEmail }}
            atlassian_user_token: ${{ secrets.atlassianUserToken }}
